export type ToolCategory =
  | 'json'
  | 'typescript'
  | 'mongodb'
  | 'postgresql'
  | 'security'
  | 'api'
  | 'datetime'
  | 'string'
  | 'devutils'

export interface ToolMetadata {
  id: string
  title: string
  category: ToolCategory
  description: string
  keywords: string[]
  inputType: 'text' | 'json' | 'code' | 'dual' | 'form' | 'none'
  outputType: 'text' | 'json' | 'code' | 'diff' | 'tree' | 'preview'
  supportsLiveTransform: boolean
  supportsFileUpload: boolean
  supportsHistory: boolean
  supportsShare: boolean
  implemented: boolean
}

export const categoryLabels: Record<ToolCategory, string> = {
  json: 'Data / JSON',
  typescript: 'TypeScript',
  mongodb: 'MongoDB',
  postgresql: 'PostgreSQL',
  security: 'Security / Encoding',
  api: 'API / HTTP',
  datetime: 'Date / Time',
  string: 'String / Text',
  devutils: 'Dev Utils',
}

export const categoryIcons: Record<ToolCategory, string> = {
  json: 'Braces',
  typescript: 'FileCode2',
  mongodb: 'Database',
  postgresql: 'Table',
  security: 'Shield',
  api: 'Globe',
  datetime: 'Clock',
  string: 'Type',
  devutils: 'Wrench',
}

export const tools: ToolMetadata[] = [
  // JSON Tools
  {
    id: 'json-beautifier',
    title: 'JSON Beautifier',
    category: 'json',
    description: 'Format and pretty print JSON with indentation',
    keywords: ['format', 'pretty', 'indent', 'beautify'],
    inputType: 'json',
    outputType: 'json',
    supportsLiveTransform: true,
    supportsFileUpload: true,
    supportsHistory: true,
    supportsShare: true,
    implemented: true,
  },
  {
    id: 'json-minifier',
    title: 'JSON Minifier',
    category: 'json',
    description: 'Minify JSON by removing whitespace',
    keywords: ['minify', 'compress', 'compact'],
    inputType: 'json',
    outputType: 'json',
    supportsLiveTransform: true,
    supportsFileUpload: true,
    supportsHistory: true,
    supportsShare: true,
    implemented: true,
  },
  {
    id: 'json-validator',
    title: 'JSON Validator',
    category: 'json',
    description: 'Validate JSON and show detailed errors',
    keywords: ['validate', 'check', 'lint', 'error'],
    inputType: 'json',
    outputType: 'text',
    supportsLiveTransform: true,
    supportsFileUpload: true,
    supportsHistory: true,
    supportsShare: true,
    implemented: true,
  },
  {
    id: 'json-diff',
    title: 'JSON Diff',
    category: 'json',
    description: 'Compare two JSON objects side by side',
    keywords: ['compare', 'difference', 'diff'],
    inputType: 'dual',
    outputType: 'diff',
    supportsLiveTransform: true,
    supportsFileUpload: true,
    supportsHistory: true,
    supportsShare: true,
    implemented: true,
  },
  {
    id: 'json-merge',
    title: 'JSON Merge',
    category: 'json',
    description: 'Deep merge multiple JSON objects',
    keywords: ['merge', 'combine', 'join'],
    inputType: 'dual',
    outputType: 'json',
    supportsLiveTransform: true,
    supportsFileUpload: true,
    supportsHistory: true,
    supportsShare: false,
    implemented: true,
  },
  {
    id: 'json-to-typescript',
    title: 'JSON to TypeScript',
    category: 'json',
    description: 'Generate TypeScript interfaces from JSON',
    keywords: ['typescript', 'types', 'interface', 'convert'],
    inputType: 'json',
    outputType: 'code',
    supportsLiveTransform: true,
    supportsFileUpload: true,
    supportsHistory: true,
    supportsShare: true,
    implemented: true,
  },
  {
    id: 'json-to-zod',
    title: 'JSON to Zod',
    category: 'json',
    description: 'Generate Zod schema from JSON',
    keywords: ['zod', 'schema', 'validation'],
    inputType: 'json',
    outputType: 'code',
    supportsLiveTransform: true,
    supportsFileUpload: true,
    supportsHistory: true,
    supportsShare: true,
    implemented: true,
  },
  {
    id: 'json-to-mongoose',
    title: 'JSON to Mongoose',
    category: 'json',
    description: 'Generate Mongoose schema from JSON',
    keywords: ['mongoose', 'mongodb', 'schema'],
    inputType: 'json',
    outputType: 'code',
    supportsLiveTransform: true,
    supportsFileUpload: true,
    supportsHistory: true,
    supportsShare: true,
    implemented: true,
  },
  {
    id: 'json-to-sql',
    title: 'JSON to SQL',
    category: 'json',
    description: 'Generate SQL INSERT statements from JSON',
    keywords: ['sql', 'insert', 'database'],
    inputType: 'json',
    outputType: 'code',
    supportsLiveTransform: true,
    supportsFileUpload: true,
    supportsHistory: true,
    supportsShare: true,
    implemented: true,
  },
  {
    id: 'json-to-csv',
    title: 'JSON to CSV',
    category: 'json',
    description: 'Convert JSON array to CSV format',
    keywords: ['csv', 'export', 'spreadsheet'],
    inputType: 'json',
    outputType: 'text',
    supportsLiveTransform: true,
    supportsFileUpload: true,
    supportsHistory: true,
    supportsShare: true,
    implemented: true,
  },
  {
    id: 'json-yaml',
    title: 'JSON <-> YAML',
    category: 'json',
    description: 'Convert between JSON and YAML',
    keywords: ['yaml', 'yml', 'convert'],
    inputType: 'text',
    outputType: 'text',
    supportsLiveTransform: true,
    supportsFileUpload: true,
    supportsHistory: true,
    supportsShare: true,
    implemented: true,
  },
  {
    id: 'json-path',
    title: 'JSON Path Extractor',
    category: 'json',
    description: 'Extract values using JSONPath expressions',
    keywords: ['jsonpath', 'query', 'extract'],
    inputType: 'json',
    outputType: 'json',
    supportsLiveTransform: true,
    supportsFileUpload: true,
    supportsHistory: true,
    supportsShare: true,
    implemented: true,
  },

  // TypeScript Tools
  {
    id: 'ts-to-js',
    title: 'TS to JS Transpiler',
    category: 'typescript',
    description: 'Transpile TypeScript to JavaScript',
    keywords: ['transpile', 'compile', 'javascript'],
    inputType: 'code',
    outputType: 'code',
    supportsLiveTransform: true,
    supportsFileUpload: true,
    supportsHistory: true,
    supportsShare: true,
    implemented: true,
  },
  {
    id: 'type-generator',
    title: 'Type Generator',
    category: 'typescript',
    description: 'Generate types from data structures',
    keywords: ['types', 'interface', 'generate'],
    inputType: 'json',
    outputType: 'code',
    supportsLiveTransform: true,
    supportsFileUpload: true,
    supportsHistory: true,
    supportsShare: true,
    implemented: true,
  },
  {
    id: 'ts-formatter',
    title: 'Type Formatter',
    category: 'typescript',
    description: 'Format TypeScript code',
    keywords: ['format', 'prettier', 'beautify'],
    inputType: 'code',
    outputType: 'code',
    supportsLiveTransform: true,
    supportsFileUpload: true,
    supportsHistory: true,
    supportsShare: true,
    implemented: true,
  },
  {
    id: 'ts-ast',
    title: 'TS AST Viewer',
    category: 'typescript',
    description: 'Visualize TypeScript AST tree',
    keywords: ['ast', 'syntax', 'tree', 'parse'],
    inputType: 'code',
    outputType: 'tree',
    supportsLiveTransform: true,
    supportsFileUpload: true,
    supportsHistory: true,
    supportsShare: false,
    implemented: true,
  },
  {
    id: 'enum-generator',
    title: 'Enum Generator',
    category: 'typescript',
    description: 'Generate enums from list of values',
    keywords: ['enum', 'const', 'generate'],
    inputType: 'form',
    outputType: 'code',
    supportsLiveTransform: true,
    supportsFileUpload: false,
    supportsHistory: true,
    supportsShare: true,
    implemented: true,
  },
  {
    id: 'interface-builder',
    title: 'Interface Builder',
    category: 'typescript',
    description: 'Build TypeScript interfaces visually',
    keywords: ['interface', 'builder', 'visual'],
    inputType: 'form',
    outputType: 'code',
    supportsLiveTransform: true,
    supportsFileUpload: false,
    supportsHistory: true,
    supportsShare: true,
    implemented: true,
  },

  // MongoDB Tools
  {
    id: 'objectid-generator',
    title: 'ObjectId Generator',
    category: 'mongodb',
    description: 'Generate valid MongoDB ObjectIds',
    keywords: ['objectid', 'mongo', 'generate'],
    inputType: 'none',
    outputType: 'text',
    supportsLiveTransform: false,
    supportsFileUpload: false,
    supportsHistory: true,
    supportsShare: false,
    implemented: true,
  },
  {
    id: 'objectid-parser',
    title: 'ObjectId Parser',
    category: 'mongodb',
    description: 'Parse ObjectId and extract timestamp',
    keywords: ['objectid', 'parse', 'timestamp'],
    inputType: 'text',
    outputType: 'json',
    supportsLiveTransform: true,
    supportsFileUpload: false,
    supportsHistory: true,
    supportsShare: true,
    implemented: true,
  },
  {
    id: 'mongo-query-builder',
    title: 'Query Builder',
    category: 'mongodb',
    description: 'Build MongoDB queries visually',
    keywords: ['query', 'filter', 'find'],
    inputType: 'form',
    outputType: 'json',
    supportsLiveTransform: true,
    supportsFileUpload: false,
    supportsHistory: true,
    supportsShare: true,
    implemented: true,
  },
  {
    id: 'aggregation-builder',
    title: 'Aggregation Builder',
    category: 'mongodb',
    description: 'Build aggregation pipelines visually',
    keywords: ['aggregation', 'pipeline', 'stages'],
    inputType: 'form',
    outputType: 'json',
    supportsLiveTransform: true,
    supportsFileUpload: false,
    supportsHistory: true,
    supportsShare: true,
    implemented: true,
  },
  {
    id: 'bson-json',
    title: 'BSON <-> JSON',
    category: 'mongodb',
    description: 'Convert between BSON and JSON',
    keywords: ['bson', 'convert'],
    inputType: 'text',
    outputType: 'text',
    supportsLiveTransform: true,
    supportsFileUpload: true,
    supportsHistory: true,
    supportsShare: true,
    implemented: true,
  },
  {
    id: 'mongo-filter-tester',
    title: 'Filter Tester',
    category: 'mongodb',
    description: 'Test filters against sample data',
    keywords: ['filter', 'test', 'match'],
    inputType: 'dual',
    outputType: 'json',
    supportsLiveTransform: true,
    supportsFileUpload: true,
    supportsHistory: true,
    supportsShare: true,
    implemented: true,
  },

  // PostgreSQL Tools
  {
    id: 'sql-formatter',
    title: 'SQL Formatter',
    category: 'postgresql',
    description: 'Format and beautify SQL queries',
    keywords: ['format', 'beautify', 'sql'],
    inputType: 'code',
    outputType: 'code',
    supportsLiveTransform: true,
    supportsFileUpload: true,
    supportsHistory: true,
    supportsShare: true,
    implemented: true,
  },
  {
    id: 'sql-to-typeorm',
    title: 'SQL to TypeORM',
    category: 'postgresql',
    description: 'Generate TypeORM entity from SQL',
    keywords: ['typeorm', 'entity', 'convert'],
    inputType: 'code',
    outputType: 'code',
    supportsLiveTransform: true,
    supportsFileUpload: true,
    supportsHistory: true,
    supportsShare: true,
    implemented: true,
  },
  {
    id: 'sql-to-prisma',
    title: 'SQL to Prisma',
    category: 'postgresql',
    description: 'Generate Prisma schema from SQL',
    keywords: ['prisma', 'schema', 'convert'],
    inputType: 'code',
    outputType: 'code',
    supportsLiveTransform: true,
    supportsFileUpload: true,
    supportsHistory: true,
    supportsShare: true,
    implemented: true,
  },
  {
    id: 'sql-query-builder',
    title: 'Query Builder',
    category: 'postgresql',
    description: 'Build SQL SELECT queries visually',
    keywords: ['select', 'query', 'builder'],
    inputType: 'form',
    outputType: 'code',
    supportsLiveTransform: true,
    supportsFileUpload: false,
    supportsHistory: true,
    supportsShare: true,
    implemented: true,
  },
  {
    id: 'explain-visualizer',
    title: 'Explain Visualizer',
    category: 'postgresql',
    description: 'Visualize EXPLAIN plan output',
    keywords: ['explain', 'plan', 'visualize'],
    inputType: 'text',
    outputType: 'tree',
    supportsLiveTransform: true,
    supportsFileUpload: true,
    supportsHistory: true,
    supportsShare: false,
    implemented: true,
  },
  {
    id: 'uuid-generator',
    title: 'UUID Generator',
    category: 'postgresql',
    description: 'Generate UUID v4 and v7',
    keywords: ['uuid', 'generate', 'guid'],
    inputType: 'none',
    outputType: 'text',
    supportsLiveTransform: false,
    supportsFileUpload: false,
    supportsHistory: true,
    supportsShare: false,
    implemented: true,
  },

  // Security Tools
  {
    id: 'base64',
    title: 'Base64 Encode/Decode',
    category: 'security',
    description: 'Encode and decode Base64 strings',
    keywords: ['base64', 'encode', 'decode'],
    inputType: 'text',
    outputType: 'text',
    supportsLiveTransform: true,
    supportsFileUpload: true,
    supportsHistory: true,
    supportsShare: true,
    implemented: true,
  },
  {
    id: 'jwt-decoder',
    title: 'JWT Decoder',
    category: 'security',
    description: 'Decode JWT header and payload',
    keywords: ['jwt', 'token', 'decode'],
    inputType: 'text',
    outputType: 'json',
    supportsLiveTransform: true,
    supportsFileUpload: false,
    supportsHistory: true,
    supportsShare: true,
    implemented: true,
  },
  {
    id: 'jwt-generator',
    title: 'JWT Generator',
    category: 'security',
    description: 'Create JWT tokens with HS256',
    keywords: ['jwt', 'token', 'generate'],
    inputType: 'form',
    outputType: 'text',
    supportsLiveTransform: true,
    supportsFileUpload: false,
    supportsHistory: true,
    supportsShare: false,
    implemented: true,
  },
  {
    id: 'hash-generator',
    title: 'Hash Generator',
    category: 'security',
    description: 'Generate SHA-256 and other hashes',
    keywords: ['hash', 'sha256', 'md5'],
    inputType: 'text',
    outputType: 'text',
    supportsLiveTransform: true,
    supportsFileUpload: true,
    supportsHistory: true,
    supportsShare: false,
    implemented: true,
  },
  {
    id: 'url-encode',
    title: 'URL Encode/Decode',
    category: 'security',
    description: 'Encode and decode URL components',
    keywords: ['url', 'encode', 'decode', 'percent'],
    inputType: 'text',
    outputType: 'text',
    supportsLiveTransform: true,
    supportsFileUpload: false,
    supportsHistory: true,
    supportsShare: true,
    implemented: true,
  },
  {
    id: 'hmac-generator',
    title: 'HMAC Generator',
    category: 'security',
    description: 'Create HMAC signatures',
    keywords: ['hmac', 'signature', 'auth'],
    inputType: 'form',
    outputType: 'text',
    supportsLiveTransform: true,
    supportsFileUpload: false,
    supportsHistory: true,
    supportsShare: false,
    implemented: true,
  },

  // API Tools
  {
    id: 'curl-to-fetch',
    title: 'Curl to Fetch',
    category: 'api',
    description: 'Convert curl commands to fetch code',
    keywords: ['curl', 'fetch', 'convert'],
    inputType: 'text',
    outputType: 'code',
    supportsLiveTransform: true,
    supportsFileUpload: false,
    supportsHistory: true,
    supportsShare: true,
    implemented: true,
  },
  {
    id: 'curl-to-axios',
    title: 'Curl to Axios',
    category: 'api',
    description: 'Convert curl commands to axios code',
    keywords: ['curl', 'axios', 'convert'],
    inputType: 'text',
    outputType: 'code',
    supportsLiveTransform: true,
    supportsFileUpload: false,
    supportsHistory: true,
    supportsShare: true,
    implemented: true,
  },
  {
    id: 'headers-parser',
    title: 'Headers Parser',
    category: 'api',
    description: 'Parse HTTP headers to JSON',
    keywords: ['headers', 'http', 'parse'],
    inputType: 'text',
    outputType: 'json',
    supportsLiveTransform: true,
    supportsFileUpload: false,
    supportsHistory: true,
    supportsShare: true,
    implemented: true,
  },
  {
    id: 'query-params-builder',
    title: 'Query Params Builder',
    category: 'api',
    description: 'Build URL query strings',
    keywords: ['query', 'params', 'url'],
    inputType: 'form',
    outputType: 'text',
    supportsLiveTransform: true,
    supportsFileUpload: false,
    supportsHistory: true,
    supportsShare: true,
    implemented: true,
  },
  {
    id: 'mock-data',
    title: 'Mock Data Generator',
    category: 'api',
    description: 'Generate fake API response data',
    keywords: ['mock', 'fake', 'data'],
    inputType: 'form',
    outputType: 'json',
    supportsLiveTransform: true,
    supportsFileUpload: false,
    supportsHistory: true,
    supportsShare: true,
    implemented: true,
  },

  // Date/Time Tools
  {
    id: 'timestamp-converter',
    title: 'Timestamp Converter',
    category: 'datetime',
    description: 'Convert between timestamps and dates',
    keywords: ['timestamp', 'unix', 'epoch'],
    inputType: 'text',
    outputType: 'json',
    supportsLiveTransform: true,
    supportsFileUpload: false,
    supportsHistory: true,
    supportsShare: true,
    implemented: true,
  },
  {
    id: 'iso-formatter',
    title: 'ISO Formatter',
    category: 'datetime',
    description: 'Parse and format ISO date strings',
    keywords: ['iso', 'date', 'format'],
    inputType: 'text',
    outputType: 'json',
    supportsLiveTransform: true,
    supportsFileUpload: false,
    supportsHistory: true,
    supportsShare: true,
    implemented: true,
  },
  {
    id: 'timezone-converter',
    title: 'Timezone Converter',
    category: 'datetime',
    description: 'Convert times between timezones',
    keywords: ['timezone', 'convert', 'utc'],
    inputType: 'form',
    outputType: 'json',
    supportsLiveTransform: true,
    supportsFileUpload: false,
    supportsHistory: true,
    supportsShare: true,
    implemented: true,
  },
  {
    id: 'date-diff',
    title: 'Date Diff',
    category: 'datetime',
    description: 'Calculate difference between dates',
    keywords: ['diff', 'difference', 'duration'],
    inputType: 'form',
    outputType: 'json',
    supportsLiveTransform: true,
    supportsFileUpload: false,
    supportsHistory: true,
    supportsShare: true,
    implemented: true,
  },
  {
    id: 'cron-parser',
    title: 'Cron Parser',
    category: 'datetime',
    description: 'Parse cron expressions to readable text',
    keywords: ['cron', 'schedule', 'parse'],
    inputType: 'text',
    outputType: 'text',
    supportsLiveTransform: true,
    supportsFileUpload: false,
    supportsHistory: true,
    supportsShare: true,
    implemented: true,
  },

  // String Tools
  {
    id: 'case-converter',
    title: 'Case Converter',
    category: 'string',
    description: 'Convert between case styles',
    keywords: ['camel', 'snake', 'kebab', 'pascal'],
    inputType: 'text',
    outputType: 'text',
    supportsLiveTransform: true,
    supportsFileUpload: false,
    supportsHistory: true,
    supportsShare: true,
    implemented: true,
  },
  {
    id: 'slug-generator',
    title: 'Slug Generator',
    category: 'string',
    description: 'Generate URL-safe slugs',
    keywords: ['slug', 'url', 'seo'],
    inputType: 'text',
    outputType: 'text',
    supportsLiveTransform: true,
    supportsFileUpload: false,
    supportsHistory: true,
    supportsShare: true,
    implemented: true,
  },
  {
    id: 'regex-tester',
    title: 'Regex Tester',
    category: 'string',
    description: 'Test regular expressions',
    keywords: ['regex', 'regexp', 'match'],
    inputType: 'form',
    outputType: 'json',
    supportsLiveTransform: true,
    supportsFileUpload: false,
    supportsHistory: true,
    supportsShare: true,
    implemented: true,
  },
  {
    id: 'text-diff',
    title: 'Text Diff',
    category: 'string',
    description: 'Compare two text blocks',
    keywords: ['diff', 'compare', 'text'],
    inputType: 'dual',
    outputType: 'diff',
    supportsLiveTransform: true,
    supportsFileUpload: true,
    supportsHistory: true,
    supportsShare: true,
    implemented: true,
  },
  {
    id: 'string-escape',
    title: 'String Escape/Unescape',
    category: 'string',
    description: 'Escape or unescape special characters',
    keywords: ['escape', 'unescape', 'quote'],
    inputType: 'text',
    outputType: 'text',
    supportsLiveTransform: true,
    supportsFileUpload: false,
    supportsHistory: true,
    supportsShare: true,
    implemented: true,
  },

  // Dev Utils
  {
    id: 'env-json',
    title: '.env <-> JSON',
    category: 'devutils',
    description: 'Convert between .env and JSON',
    keywords: ['env', 'json', 'convert'],
    inputType: 'text',
    outputType: 'text',
    supportsLiveTransform: true,
    supportsFileUpload: true,
    supportsHistory: true,
    supportsShare: true,
    implemented: true,
  },
  {
    id: 'color-converter',
    title: 'Color Converter',
    category: 'devutils',
    description: 'Convert between HEX, RGB, and HSL',
    keywords: ['color', 'hex', 'rgb', 'hsl'],
    inputType: 'text',
    outputType: 'json',
    supportsLiveTransform: true,
    supportsFileUpload: false,
    supportsHistory: true,
    supportsShare: true,
    implemented: true,
  },
  {
    id: 'random-generator',
    title: 'Random Generator',
    category: 'devutils',
    description: 'Generate random strings and numbers',
    keywords: ['random', 'generate', 'string'],
    inputType: 'form',
    outputType: 'text',
    supportsLiveTransform: false,
    supportsFileUpload: false,
    supportsHistory: true,
    supportsShare: false,
    implemented: true,
  },
  {
    id: 'nanoid-generator',
    title: 'NanoID Generator',
    category: 'devutils',
    description: 'Generate short unique IDs',
    keywords: ['nanoid', 'id', 'short'],
    inputType: 'form',
    outputType: 'text',
    supportsLiveTransform: false,
    supportsFileUpload: false,
    supportsHistory: true,
    supportsShare: false,
    implemented: true,
  },
]

export function getToolsByCategory(category: ToolCategory): ToolMetadata[] {
  return tools.filter((tool) => tool.category === category)
}

export function getToolById(id: string): ToolMetadata | undefined {
  return tools.find((tool) => tool.id === id)
}

export function searchTools(query: string): ToolMetadata[] {
  const lowerQuery = query.toLowerCase()
  return tools.filter(
    (tool) =>
      tool.title.toLowerCase().includes(lowerQuery) ||
      tool.description.toLowerCase().includes(lowerQuery) ||
      tool.keywords.some((kw) => kw.toLowerCase().includes(lowerQuery))
  )
}

export function getCategories(): ToolCategory[] {
  return Object.keys(categoryLabels) as ToolCategory[]
}

// Group tools by category for UI rendering
export interface CategoryGroup {
  slug: ToolCategory;
  name: string;
  icon: string;
  tools: ToolMetadata[];
}

export function getToolRegistry(): CategoryGroup[] {
  const categories = getCategories();
  return categories.map((cat) => ({
    slug: cat,
    name: categoryLabels[cat],
    icon: categoryIcons[cat],
    tools: getToolsByCategory(cat),
  }));
}

// Alias for backward compatibility
export const TOOL_REGISTRY = getToolRegistry();

// Featured tools (most commonly used)
export const FEATURED_TOOLS = [
  'json-beautifier',
  'json-to-typescript',
  'jwt-decoder',
  'timestamp-converter',
  'base64',
  'uuid-generator',
  'regex-tester',
  'case-converter',
  'color-converter',
];

// Helper to generate tool URL
export function getToolUrl(categorySlug: string, toolId: string): string {
  return `/tools/${categorySlug}/${toolId}`;
}

// Helper to get tool by slug
export function getToolBySlug(categorySlug: string, toolSlug: string): ToolMetadata | undefined {
  return tools.find((t) => t.category === categorySlug && t.id === toolSlug);
}

// Re-export Tool type for convenience
export type Tool = ToolMetadata;
