export type ToolCategory =
  | 'json'
  | 'typescript'
  | 'mongodb'
  | 'postgresql'
  | 'security'
  | 'api'
  | 'datetime'
  | 'string'
  | 'devutils'
  | 'css'
  | 'html'
  | 'converter'
  | 'media'

export interface ToolMetadata {
  id: string
  title: string
  category: ToolCategory
  description: string
  keywords: string[]
  inputType: 'text' | 'json' | 'code' | 'dual' | 'form' | 'none'
  outputType: 'text' | 'json' | 'code' | 'diff' | 'tree' | 'preview'
  supportsLiveTransform: boolean
  supportsFileUpload: boolean
  supportsHistory: boolean
  supportsShare: boolean
  implemented: boolean
}

export const categoryLabels: Record<ToolCategory, string> = {
  json: 'Data / JSON',
  typescript: 'TypeScript',
  mongodb: 'MongoDB',
  postgresql: 'PostgreSQL',
  security: 'Security / Encoding',
  api: 'API / HTTP',
  datetime: 'Date / Time',
  string: 'String / Text',
  devutils: 'Dev Utils',
  css: 'CSS',
  html: 'HTML / Markup',
  converter: 'Converters',
  media: 'Media',
}

export const categoryIcons: Record<ToolCategory, string> = {
  json: 'Braces',
  typescript: 'FileCode2',
  mongodb: 'Database',
  postgresql: 'Table',
  security: 'Shield',
  api: 'Globe',
  datetime: 'Clock',
  string: 'Type',
  devutils: 'Wrench',
  css: 'Palette',
  html: 'Code',
  converter: 'ArrowLeftRight',
  media: 'Film',
}

export const tools: ToolMetadata[] = [
  // JSON Tools
  {
    id: 'json-beautifier',
    title: 'JSON Beautifier',
    category: 'json',
    description: 'Format and pretty print JSON with indentation',
    keywords: ['format', 'pretty', 'indent', 'beautify'],
    inputType: 'json',
    outputType: 'json',
    supportsLiveTransform: true,
    supportsFileUpload: true,
    supportsHistory: true,
    supportsShare: true,
    implemented: true,
  },
  {
    id: 'json-minifier',
    title: 'JSON Minifier',
    category: 'json',
    description: 'Minify JSON by removing whitespace',
    keywords: ['minify', 'compress', 'compact'],
    inputType: 'json',
    outputType: 'json',
    supportsLiveTransform: true,
    supportsFileUpload: true,
    supportsHistory: true,
    supportsShare: true,
    implemented: true,
  },
  {
    id: 'json-validator',
    title: 'JSON Validator',
    category: 'json',
    description: 'Validate JSON and show detailed errors',
    keywords: ['validate', 'check', 'lint', 'error'],
    inputType: 'json',
    outputType: 'text',
    supportsLiveTransform: true,
    supportsFileUpload: true,
    supportsHistory: true,
    supportsShare: true,
    implemented: true,
  },
  {
    id: 'json-diff',
    title: 'JSON Diff',
    category: 'json',
    description: 'Compare two JSON objects side by side',
    keywords: ['compare', 'difference', 'diff'],
    inputType: 'dual',
    outputType: 'diff',
    supportsLiveTransform: true,
    supportsFileUpload: true,
    supportsHistory: true,
    supportsShare: true,
    implemented: true,
  },
  {
    id: 'json-merge',
    title: 'JSON Merge',
    category: 'json',
    description: 'Deep merge multiple JSON objects',
    keywords: ['merge', 'combine', 'join'],
    inputType: 'dual',
    outputType: 'json',
    supportsLiveTransform: true,
    supportsFileUpload: true,
    supportsHistory: true,
    supportsShare: false,
    implemented: true,
  },
  {
    id: 'json-to-typescript',
    title: 'JSON to TypeScript',
    category: 'json',
    description: 'Generate TypeScript interfaces from JSON',
    keywords: ['typescript', 'types', 'interface', 'convert'],
    inputType: 'json',
    outputType: 'code',
    supportsLiveTransform: true,
    supportsFileUpload: true,
    supportsHistory: true,
    supportsShare: true,
    implemented: true,
  },
  {
    id: 'json-to-zod',
    title: 'JSON to Zod',
    category: 'json',
    description: 'Generate Zod schema from JSON',
    keywords: ['zod', 'schema', 'validation'],
    inputType: 'json',
    outputType: 'code',
    supportsLiveTransform: true,
    supportsFileUpload: true,
    supportsHistory: true,
    supportsShare: true,
    implemented: true,
  },
  {
    id: 'json-to-mongoose',
    title: 'JSON to Mongoose',
    category: 'json',
    description: 'Generate Mongoose schema from JSON',
    keywords: ['mongoose', 'mongodb', 'schema'],
    inputType: 'json',
    outputType: 'code',
    supportsLiveTransform: true,
    supportsFileUpload: true,
    supportsHistory: true,
    supportsShare: true,
    implemented: true,
  },
  {
    id: 'json-to-sql',
    title: 'JSON to SQL',
    category: 'json',
    description: 'Generate SQL INSERT statements from JSON',
    keywords: ['sql', 'insert', 'database'],
    inputType: 'json',
    outputType: 'code',
    supportsLiveTransform: true,
    supportsFileUpload: true,
    supportsHistory: true,
    supportsShare: true,
    implemented: true,
  },
  {
    id: 'json-to-csv',
    title: 'JSON to CSV',
    category: 'json',
    description: 'Convert JSON array to CSV format',
    keywords: ['csv', 'export', 'spreadsheet'],
    inputType: 'json',
    outputType: 'text',
    supportsLiveTransform: true,
    supportsFileUpload: true,
    supportsHistory: true,
    supportsShare: true,
    implemented: true,
  },
  {
    id: 'json-yaml',
    title: 'JSON <-> YAML',
    category: 'json',
    description: 'Convert between JSON and YAML',
    keywords: ['yaml', 'yml', 'convert'],
    inputType: 'text',
    outputType: 'text',
    supportsLiveTransform: true,
    supportsFileUpload: true,
    supportsHistory: true,
    supportsShare: true,
    implemented: true,
  },
  {
    id: 'json-path',
    title: 'JSON Path Extractor',
    category: 'json',
    description: 'Extract values using JSONPath expressions',
    keywords: ['jsonpath', 'query', 'extract'],
    inputType: 'json',
    outputType: 'json',
    supportsLiveTransform: true,
    supportsFileUpload: true,
    supportsHistory: true,
    supportsShare: true,
    implemented: true,
  },

  // TypeScript Tools
  {
    id: 'ts-to-js',
    title: 'TS to JS Transpiler',
    category: 'typescript',
    description: 'Transpile TypeScript to JavaScript',
    keywords: ['transpile', 'compile', 'javascript'],
    inputType: 'code',
    outputType: 'code',
    supportsLiveTransform: true,
    supportsFileUpload: true,
    supportsHistory: true,
    supportsShare: true,
    implemented: true,
  },
  {
    id: 'type-generator',
    title: 'Type Generator',
    category: 'typescript',
    description: 'Generate types from data structures',
    keywords: ['types', 'interface', 'generate'],
    inputType: 'json',
    outputType: 'code',
    supportsLiveTransform: true,
    supportsFileUpload: true,
    supportsHistory: true,
    supportsShare: true,
    implemented: true,
  },
  {
    id: 'ts-formatter',
    title: 'Type Formatter',
    category: 'typescript',
    description: 'Format TypeScript code',
    keywords: ['format', 'prettier', 'beautify'],
    inputType: 'code',
    outputType: 'code',
    supportsLiveTransform: true,
    supportsFileUpload: true,
    supportsHistory: true,
    supportsShare: true,
    implemented: true,
  },
  {
    id: 'ts-ast',
    title: 'TS AST Viewer',
    category: 'typescript',
    description: 'Visualize TypeScript AST tree',
    keywords: ['ast', 'syntax', 'tree', 'parse'],
    inputType: 'code',
    outputType: 'tree',
    supportsLiveTransform: true,
    supportsFileUpload: true,
    supportsHistory: true,
    supportsShare: false,
    implemented: true,
  },
  {
    id: 'enum-generator',
    title: 'Enum Generator',
    category: 'typescript',
    description: 'Generate enums from list of values',
    keywords: ['enum', 'const', 'generate'],
    inputType: 'form',
    outputType: 'code',
    supportsLiveTransform: true,
    supportsFileUpload: false,
    supportsHistory: true,
    supportsShare: true,
    implemented: true,
  },
  {
    id: 'interface-builder',
    title: 'Interface Builder',
    category: 'typescript',
    description: 'Build TypeScript interfaces visually',
    keywords: ['interface', 'builder', 'visual'],
    inputType: 'form',
    outputType: 'code',
    supportsLiveTransform: true,
    supportsFileUpload: false,
    supportsHistory: true,
    supportsShare: true,
    implemented: true,
  },

  // MongoDB Tools
  {
    id: 'objectid-generator',
    title: 'ObjectId Generator',
    category: 'mongodb',
    description: 'Generate valid MongoDB ObjectIds',
    keywords: ['objectid', 'mongo', 'generate'],
    inputType: 'none',
    outputType: 'text',
    supportsLiveTransform: false,
    supportsFileUpload: false,
    supportsHistory: true,
    supportsShare: false,
    implemented: true,
  },
  {
    id: 'objectid-parser',
    title: 'ObjectId Parser',
    category: 'mongodb',
    description: 'Parse ObjectId and extract timestamp',
    keywords: ['objectid', 'parse', 'timestamp'],
    inputType: 'text',
    outputType: 'json',
    supportsLiveTransform: true,
    supportsFileUpload: false,
    supportsHistory: true,
    supportsShare: true,
    implemented: true,
  },
  {
    id: 'mongo-query-builder',
    title: 'Query Builder',
    category: 'mongodb',
    description: 'Build MongoDB queries visually',
    keywords: ['query', 'filter', 'find'],
    inputType: 'form',
    outputType: 'json',
    supportsLiveTransform: true,
    supportsFileUpload: false,
    supportsHistory: true,
    supportsShare: true,
    implemented: true,
  },
  {
    id: 'aggregation-builder',
    title: 'Aggregation Builder',
    category: 'mongodb',
    description: 'Build aggregation pipelines visually',
    keywords: ['aggregation', 'pipeline', 'stages'],
    inputType: 'form',
    outputType: 'json',
    supportsLiveTransform: true,
    supportsFileUpload: false,
    supportsHistory: true,
    supportsShare: true,
    implemented: true,
  },
  {
    id: 'bson-json',
    title: 'BSON <-> JSON',
    category: 'mongodb',
    description: 'Convert between BSON and JSON',
    keywords: ['bson', 'convert'],
    inputType: 'text',
    outputType: 'text',
    supportsLiveTransform: true,
    supportsFileUpload: true,
    supportsHistory: true,
    supportsShare: true,
    implemented: true,
  },
  {
    id: 'mongo-filter-tester',
    title: 'Filter Tester',
    category: 'mongodb',
    description: 'Test filters against sample data',
    keywords: ['filter', 'test', 'match'],
    inputType: 'dual',
    outputType: 'json',
    supportsLiveTransform: true,
    supportsFileUpload: true,
    supportsHistory: true,
    supportsShare: true,
    implemented: true,
  },

  // PostgreSQL Tools
  {
    id: 'sql-formatter',
    title: 'SQL Formatter',
    category: 'postgresql',
    description: 'Format and beautify SQL queries',
    keywords: ['format', 'beautify', 'sql'],
    inputType: 'code',
    outputType: 'code',
    supportsLiveTransform: true,
    supportsFileUpload: true,
    supportsHistory: true,
    supportsShare: true,
    implemented: true,
  },
  {
    id: 'sql-to-typeorm',
    title: 'SQL to TypeORM',
    category: 'postgresql',
    description: 'Generate TypeORM entity from SQL',
    keywords: ['typeorm', 'entity', 'convert'],
    inputType: 'code',
    outputType: 'code',
    supportsLiveTransform: true,
    supportsFileUpload: true,
    supportsHistory: true,
    supportsShare: true,
    implemented: true,
  },
  {
    id: 'sql-to-prisma',
    title: 'SQL to Prisma',
    category: 'postgresql',
    description: 'Generate Prisma schema from SQL',
    keywords: ['prisma', 'schema', 'convert'],
    inputType: 'code',
    outputType: 'code',
    supportsLiveTransform: true,
    supportsFileUpload: true,
    supportsHistory: true,
    supportsShare: true,
    implemented: true,
  },
  {
    id: 'sql-query-builder',
    title: 'Query Builder',
    category: 'postgresql',
    description: 'Build SQL SELECT queries visually',
    keywords: ['select', 'query', 'builder'],
    inputType: 'form',
    outputType: 'code',
    supportsLiveTransform: true,
    supportsFileUpload: false,
    supportsHistory: true,
    supportsShare: true,
    implemented: true,
  },
  {
    id: 'explain-visualizer',
    title: 'Explain Visualizer',
    category: 'postgresql',
    description: 'Visualize EXPLAIN plan output',
    keywords: ['explain', 'plan', 'visualize'],
    inputType: 'text',
    outputType: 'tree',
    supportsLiveTransform: true,
    supportsFileUpload: true,
    supportsHistory: true,
    supportsShare: false,
    implemented: true,
  },
  {
    id: 'uuid-generator',
    title: 'UUID Generator',
    category: 'postgresql',
    description: 'Generate UUID v4 and v7',
    keywords: ['uuid', 'generate', 'guid'],
    inputType: 'none',
    outputType: 'text',
    supportsLiveTransform: false,
    supportsFileUpload: false,
    supportsHistory: true,
    supportsShare: false,
    implemented: true,
  },

  // Security Tools
  {
    id: 'base64',
    title: 'Base64 Encode/Decode',
    category: 'security',
    description: 'Encode and decode Base64 strings',
    keywords: ['base64', 'encode', 'decode'],
    inputType: 'text',
    outputType: 'text',
    supportsLiveTransform: true,
    supportsFileUpload: true,
    supportsHistory: true,
    supportsShare: true,
    implemented: true,
  },
  {
    id: 'jwt-decoder',
    title: 'JWT Decoder',
    category: 'security',
    description: 'Decode JWT header and payload',
    keywords: ['jwt', 'token', 'decode'],
    inputType: 'text',
    outputType: 'json',
    supportsLiveTransform: true,
    supportsFileUpload: false,
    supportsHistory: true,
    supportsShare: true,
    implemented: true,
  },
  {
    id: 'jwt-generator',
    title: 'JWT Generator',
    category: 'security',
    description: 'Create JWT tokens with HS256',
    keywords: ['jwt', 'token', 'generate'],
    inputType: 'form',
    outputType: 'text',
    supportsLiveTransform: true,
    supportsFileUpload: false,
    supportsHistory: true,
    supportsShare: false,
    implemented: true,
  },
  {
    id: 'hash-generator',
    title: 'Hash Generator',
    category: 'security',
    description: 'Generate SHA-256 and other hashes',
    keywords: ['hash', 'sha256', 'md5'],
    inputType: 'text',
    outputType: 'text',
    supportsLiveTransform: true,
    supportsFileUpload: true,
    supportsHistory: true,
    supportsShare: false,
    implemented: true,
  },
  {
    id: 'url-encode',
    title: 'URL Encode/Decode',
    category: 'security',
    description: 'Encode and decode URL components',
    keywords: ['url', 'encode', 'decode', 'percent'],
    inputType: 'text',
    outputType: 'text',
    supportsLiveTransform: true,
    supportsFileUpload: false,
    supportsHistory: true,
    supportsShare: true,
    implemented: true,
  },
  {
    id: 'hmac-generator',
    title: 'HMAC Generator',
    category: 'security',
    description: 'Create HMAC signatures',
    keywords: ['hmac', 'signature', 'auth'],
    inputType: 'form',
    outputType: 'text',
    supportsLiveTransform: true,
    supportsFileUpload: false,
    supportsHistory: true,
    supportsShare: false,
    implemented: true,
  },

  // API Tools
  {
    id: 'curl-to-fetch',
    title: 'Curl to Fetch',
    category: 'api',
    description: 'Convert curl commands to fetch code',
    keywords: ['curl', 'fetch', 'convert'],
    inputType: 'text',
    outputType: 'code',
    supportsLiveTransform: true,
    supportsFileUpload: false,
    supportsHistory: true,
    supportsShare: true,
    implemented: true,
  },
  {
    id: 'curl-to-axios',
    title: 'Curl to Axios',
    category: 'api',
    description: 'Convert curl commands to axios code',
    keywords: ['curl', 'axios', 'convert'],
    inputType: 'text',
    outputType: 'code',
    supportsLiveTransform: true,
    supportsFileUpload: false,
    supportsHistory: true,
    supportsShare: true,
    implemented: true,
  },
  {
    id: 'headers-parser',
    title: 'Headers Parser',
    category: 'api',
    description: 'Parse HTTP headers to JSON',
    keywords: ['headers', 'http', 'parse'],
    inputType: 'text',
    outputType: 'json',
    supportsLiveTransform: true,
    supportsFileUpload: false,
    supportsHistory: true,
    supportsShare: true,
    implemented: true,
  },
  {
    id: 'query-params-builder',
    title: 'Query Params Builder',
    category: 'api',
    description: 'Build URL query strings',
    keywords: ['query', 'params', 'url'],
    inputType: 'form',
    outputType: 'text',
    supportsLiveTransform: true,
    supportsFileUpload: false,
    supportsHistory: true,
    supportsShare: true,
    implemented: true,
  },
  {
    id: 'mock-data',
    title: 'Mock Data Generator',
    category: 'api',
    description: 'Generate fake API response data',
    keywords: ['mock', 'fake', 'data'],
    inputType: 'form',
    outputType: 'json',
    supportsLiveTransform: true,
    supportsFileUpload: false,
    supportsHistory: true,
    supportsShare: true,
    implemented: true,
  },

  // Date/Time Tools
  {
    id: 'timestamp-converter',
    title: 'Timestamp Converter',
    category: 'datetime',
    description: 'Convert between timestamps and dates',
    keywords: ['timestamp', 'unix', 'epoch'],
    inputType: 'text',
    outputType: 'json',
    supportsLiveTransform: true,
    supportsFileUpload: false,
    supportsHistory: true,
    supportsShare: true,
    implemented: true,
  },
  {
    id: 'iso-formatter',
    title: 'ISO Formatter',
    category: 'datetime',
    description: 'Parse and format ISO date strings',
    keywords: ['iso', 'date', 'format'],
    inputType: 'text',
    outputType: 'json',
    supportsLiveTransform: true,
    supportsFileUpload: false,
    supportsHistory: true,
    supportsShare: true,
    implemented: true,
  },
  {
    id: 'timezone-converter',
    title: 'Timezone Converter',
    category: 'datetime',
    description: 'Convert times between timezones',
    keywords: ['timezone', 'convert', 'utc'],
    inputType: 'form',
    outputType: 'json',
    supportsLiveTransform: true,
    supportsFileUpload: false,
    supportsHistory: true,
    supportsShare: true,
    implemented: true,
  },
  {
    id: 'date-diff',
    title: 'Date Diff',
    category: 'datetime',
    description: 'Calculate difference between dates',
    keywords: ['diff', 'difference', 'duration'],
    inputType: 'form',
    outputType: 'json',
    supportsLiveTransform: true,
    supportsFileUpload: false,
    supportsHistory: true,
    supportsShare: true,
    implemented: true,
  },
  {
    id: 'cron-parser',
    title: 'Cron Parser',
    category: 'datetime',
    description: 'Parse cron expressions to readable text',
    keywords: ['cron', 'schedule', 'parse'],
    inputType: 'text',
    outputType: 'text',
    supportsLiveTransform: true,
    supportsFileUpload: false,
    supportsHistory: true,
    supportsShare: true,
    implemented: true,
  },

  // String Tools
  {
    id: 'case-converter',
    title: 'Case Converter',
    category: 'string',
    description: 'Convert between case styles',
    keywords: ['camel', 'snake', 'kebab', 'pascal'],
    inputType: 'text',
    outputType: 'text',
    supportsLiveTransform: true,
    supportsFileUpload: false,
    supportsHistory: true,
    supportsShare: true,
    implemented: true,
  },
  {
    id: 'slug-generator',
    title: 'Slug Generator',
    category: 'string',
    description: 'Generate URL-safe slugs',
    keywords: ['slug', 'url', 'seo'],
    inputType: 'text',
    outputType: 'text',
    supportsLiveTransform: true,
    supportsFileUpload: false,
    supportsHistory: true,
    supportsShare: true,
    implemented: true,
  },
  {
    id: 'regex-tester',
    title: 'Regex Tester',
    category: 'string',
    description: 'Test regular expressions',
    keywords: ['regex', 'regexp', 'match'],
    inputType: 'form',
    outputType: 'json',
    supportsLiveTransform: true,
    supportsFileUpload: false,
    supportsHistory: true,
    supportsShare: true,
    implemented: true,
  },
  {
    id: 'text-diff',
    title: 'Text Diff',
    category: 'string',
    description: 'Compare two text blocks',
    keywords: ['diff', 'compare', 'text'],
    inputType: 'dual',
    outputType: 'diff',
    supportsLiveTransform: true,
    supportsFileUpload: true,
    supportsHistory: true,
    supportsShare: true,
    implemented: true,
  },
  {
    id: 'string-escape',
    title: 'String Escape/Unescape',
    category: 'string',
    description: 'Escape or unescape special characters',
    keywords: ['escape', 'unescape', 'quote'],
    inputType: 'text',
    outputType: 'text',
    supportsLiveTransform: true,
    supportsFileUpload: false,
    supportsHistory: true,
    supportsShare: true,
    implemented: true,
  },

  // Dev Utils
  {
    id: 'env-json',
    title: '.env <-> JSON',
    category: 'devutils',
    description: 'Convert between .env and JSON',
    keywords: ['env', 'json', 'convert'],
    inputType: 'text',
    outputType: 'text',
    supportsLiveTransform: true,
    supportsFileUpload: true,
    supportsHistory: true,
    supportsShare: true,
    implemented: true,
  },
  {
    id: 'color-converter',
    title: 'Color Converter',
    category: 'devutils',
    description: 'Convert between HEX, RGB, and HSL',
    keywords: ['color', 'hex', 'rgb', 'hsl'],
    inputType: 'text',
    outputType: 'json',
    supportsLiveTransform: true,
    supportsFileUpload: false,
    supportsHistory: true,
    supportsShare: true,
    implemented: true,
  },
  {
    id: 'random-generator',
    title: 'Random Generator',
    category: 'devutils',
    description: 'Generate random strings and numbers',
    keywords: ['random', 'generate', 'string'],
    inputType: 'form',
    outputType: 'text',
    supportsLiveTransform: false,
    supportsFileUpload: false,
    supportsHistory: true,
    supportsShare: false,
    implemented: true,
  },
  {
    id: 'nanoid-generator',
    title: 'NanoID Generator',
    category: 'devutils',
    description: 'Generate short unique IDs',
    keywords: ['nanoid', 'id', 'short'],
    inputType: 'form',
    outputType: 'text',
    supportsLiveTransform: false,
    supportsFileUpload: false,
    supportsHistory: true,
    supportsShare: false,
    implemented: true,
  },

  // JSON (additions)
  {
    id: 'json-to-go',
    title: 'JSON to Go',
    category: 'json',
    description: 'Generate Go structs from JSON',
    keywords: ['go', 'golang', 'struct', 'convert'],
    inputType: 'json',
    outputType: 'code',
    supportsLiveTransform: true,
    supportsFileUpload: true,
    supportsHistory: true,
    supportsShare: true,
    implemented: true,
  },
  {
    id: 'json-schema-generator',
    title: 'JSON Schema Generator',
    category: 'json',
    description: 'Generate JSON Schema from sample JSON',
    keywords: ['schema', 'jsonschema', 'generate', 'validate'],
    inputType: 'json',
    outputType: 'json',
    supportsLiveTransform: true,
    supportsFileUpload: true,
    supportsHistory: true,
    supportsShare: true,
    implemented: true,
  },

  // TypeScript (additions)
  {
    id: 'zod-to-ts',
    title: 'Zod to TypeScript',
    category: 'typescript',
    description: 'Convert Zod schema to TypeScript types',
    keywords: ['zod', 'typescript', 'types', 'convert'],
    inputType: 'code',
    outputType: 'code',
    supportsLiveTransform: true,
    supportsFileUpload: true,
    supportsHistory: true,
    supportsShare: true,
    implemented: true,
  },

  // Security (additions)
  {
    id: 'password-generator',
    title: 'Password Generator',
    category: 'security',
    description: 'Generate strong random passwords',
    keywords: ['password', 'generate', 'random', 'strong'],
    inputType: 'form',
    outputType: 'text',
    supportsLiveTransform: false,
    supportsFileUpload: false,
    supportsHistory: false,
    supportsShare: false,
    implemented: true,
  },
  {
    id: 'html-entities-encode',
    title: 'HTML Entities',
    category: 'security',
    description: 'Encode and decode HTML entities',
    keywords: ['html', 'entities', 'encode', 'decode', 'escape'],
    inputType: 'text',
    outputType: 'text',
    supportsLiveTransform: true,
    supportsFileUpload: false,
    supportsHistory: true,
    supportsShare: true,
    implemented: true,
  },
  {
    id: 'password-strength',
    title: 'Password Strength',
    category: 'security',
    description: 'Check password strength and entropy',
    keywords: ['password', 'strength', 'entropy', 'check'],
    inputType: 'text',
    outputType: 'text',
    supportsLiveTransform: true,
    supportsFileUpload: false,
    supportsHistory: false,
    supportsShare: false,
    implemented: true,
  },

  // API (additions)
  {
    id: 'api-tester',
    title: 'API Tester',
    category: 'api',
    description: 'Send HTTP requests and inspect responses',
    keywords: ['api', 'http', 'request', 'test', 'rest'],
    inputType: 'form',
    outputType: 'json',
    supportsLiveTransform: false,
    supportsFileUpload: false,
    supportsHistory: true,
    supportsShare: false,
    implemented: true,
  },
  {
    id: 'http-status-codes',
    title: 'HTTP Status Codes',
    category: 'api',
    description: 'Reference for all HTTP status codes',
    keywords: ['http', 'status', 'codes', 'reference'],
    inputType: 'text',
    outputType: 'text',
    supportsLiveTransform: true,
    supportsFileUpload: false,
    supportsHistory: false,
    supportsShare: false,
    implemented: true,
  },
  {
    id: 'graphql-formatter',
    title: 'GraphQL Formatter',
    category: 'api',
    description: 'Format and beautify GraphQL queries',
    keywords: ['graphql', 'format', 'beautify', 'gql'],
    inputType: 'code',
    outputType: 'code',
    supportsLiveTransform: true,
    supportsFileUpload: true,
    supportsHistory: true,
    supportsShare: true,
    implemented: true,
  },

  // String (additions)
  {
    id: 'word-counter',
    title: 'Word Counter',
    category: 'string',
    description: 'Count words, characters, sentences, and paragraphs',
    keywords: ['word', 'count', 'character', 'length'],
    inputType: 'text',
    outputType: 'text',
    supportsLiveTransform: true,
    supportsFileUpload: true,
    supportsHistory: false,
    supportsShare: false,
    implemented: true,
  },
  {
    id: 'lorem-generator',
    title: 'Lorem Ipsum Generator',
    category: 'string',
    description: 'Generate placeholder Lorem Ipsum text',
    keywords: ['lorem', 'ipsum', 'placeholder', 'dummy'],
    inputType: 'form',
    outputType: 'text',
    supportsLiveTransform: false,
    supportsFileUpload: false,
    supportsHistory: false,
    supportsShare: false,
    implemented: true,
  },
  {
    id: 'line-sorter',
    title: 'Line Sorter',
    category: 'string',
    description: 'Sort lines alphabetically or reverse',
    keywords: ['sort', 'lines', 'alphabetical', 'order'],
    inputType: 'text',
    outputType: 'text',
    supportsLiveTransform: true,
    supportsFileUpload: true,
    supportsHistory: true,
    supportsShare: true,
    implemented: true,
  },
  {
    id: 'text-reverse',
    title: 'Text Reverser',
    category: 'string',
    description: 'Reverse text, words, or lines',
    keywords: ['reverse', 'flip', 'mirror', 'backward'],
    inputType: 'text',
    outputType: 'text',
    supportsLiveTransform: true,
    supportsFileUpload: false,
    supportsHistory: true,
    supportsShare: true,
    implemented: true,
  },
  {
    id: 'markdown-preview',
    title: 'Markdown Preview',
    category: 'string',
    description: 'Preview rendered Markdown in real time',
    keywords: ['markdown', 'preview', 'render', 'md'],
    inputType: 'text',
    outputType: 'preview',
    supportsLiveTransform: true,
    supportsFileUpload: true,
    supportsHistory: true,
    supportsShare: true,
    implemented: true,
  },

  // Dev Utils (additions)
  {
    id: 'chmod-calculator',
    title: 'Chmod Calculator',
    category: 'devutils',
    description: 'Calculate Unix file permissions',
    keywords: ['chmod', 'permissions', 'unix', 'linux'],
    inputType: 'form',
    outputType: 'text',
    supportsLiveTransform: true,
    supportsFileUpload: false,
    supportsHistory: false,
    supportsShare: false,
    implemented: true,
  },
  {
    id: 'gitignore-generator',
    title: '.gitignore Generator',
    category: 'devutils',
    description: 'Generate .gitignore files for popular stacks',
    keywords: ['gitignore', 'git', 'ignore', 'generate'],
    inputType: 'form',
    outputType: 'text',
    supportsLiveTransform: false,
    supportsFileUpload: false,
    supportsHistory: true,
    supportsShare: true,
    implemented: true,
  },
  {
    id: 'dockerfile-generator',
    title: 'Dockerfile Generator',
    category: 'devutils',
    description: 'Generate Dockerfile for common stacks',
    keywords: ['docker', 'dockerfile', 'container', 'generate'],
    inputType: 'form',
    outputType: 'code',
    supportsLiveTransform: false,
    supportsFileUpload: false,
    supportsHistory: true,
    supportsShare: true,
    implemented: true,
  },
  {
    id: 'number-base-converter',
    title: 'Number Base Converter',
    category: 'devutils',
    description: 'Convert numbers between bases (bin, oct, dec, hex)',
    keywords: ['binary', 'hex', 'octal', 'decimal', 'base', 'convert'],
    inputType: 'text',
    outputType: 'text',
    supportsLiveTransform: true,
    supportsFileUpload: false,
    supportsHistory: true,
    supportsShare: true,
    implemented: true,
  },
  {
    id: 'ascii-table',
    title: 'ASCII Table',
    category: 'devutils',
    description: 'Interactive ASCII character reference table',
    keywords: ['ascii', 'table', 'character', 'reference', 'unicode'],
    inputType: 'text',
    outputType: 'text',
    supportsLiveTransform: true,
    supportsFileUpload: false,
    supportsHistory: false,
    supportsShare: false,
    implemented: true,
  },

  // Date/Time (additions)
  {
    id: 'date-formatter',
    title: 'Date Formatter',
    category: 'datetime',
    description: 'Format dates with custom patterns',
    keywords: ['date', 'format', 'pattern', 'strftime'],
    inputType: 'form',
    outputType: 'text',
    supportsLiveTransform: true,
    supportsFileUpload: false,
    supportsHistory: true,
    supportsShare: true,
    implemented: true,
  },

  // CSS Tools (new category)
  {
    id: 'css-minifier',
    title: 'CSS Minifier',
    category: 'css',
    description: 'Minify CSS by removing whitespace and comments',
    keywords: ['css', 'minify', 'compress', 'compact'],
    inputType: 'code',
    outputType: 'code',
    supportsLiveTransform: true,
    supportsFileUpload: true,
    supportsHistory: true,
    supportsShare: true,
    implemented: true,
  },
  {
    id: 'css-beautifier',
    title: 'CSS Beautifier',
    category: 'css',
    description: 'Format and beautify CSS code',
    keywords: ['css', 'format', 'beautify', 'pretty'],
    inputType: 'code',
    outputType: 'code',
    supportsLiveTransform: true,
    supportsFileUpload: true,
    supportsHistory: true,
    supportsShare: true,
    implemented: true,
  },
  {
    id: 'css-to-tailwind',
    title: 'CSS to Tailwind',
    category: 'css',
    description: 'Convert CSS properties to Tailwind classes',
    keywords: ['css', 'tailwind', 'convert', 'utility'],
    inputType: 'code',
    outputType: 'text',
    supportsLiveTransform: true,
    supportsFileUpload: true,
    supportsHistory: true,
    supportsShare: true,
    implemented: true,
  },
  {
    id: 'box-shadow-generator',
    title: 'Box Shadow Generator',
    category: 'css',
    description: 'Generate CSS box-shadow visually',
    keywords: ['box-shadow', 'shadow', 'css', 'generator'],
    inputType: 'form',
    outputType: 'code',
    supportsLiveTransform: true,
    supportsFileUpload: false,
    supportsHistory: true,
    supportsShare: true,
    implemented: true,
  },
  {
    id: 'flexbox-generator',
    title: 'Flexbox Playground',
    category: 'css',
    description: 'Visualize and generate flexbox CSS',
    keywords: ['flexbox', 'flex', 'layout', 'css'],
    inputType: 'form',
    outputType: 'code',
    supportsLiveTransform: true,
    supportsFileUpload: false,
    supportsHistory: true,
    supportsShare: true,
    implemented: true,
  },
  {
    id: 'gradient-generator',
    title: 'Gradient Generator',
    category: 'css',
    description: 'Create and customize CSS gradients',
    keywords: ['gradient', 'css', 'color', 'background'],
    inputType: 'form',
    outputType: 'code',
    supportsLiveTransform: true,
    supportsFileUpload: false,
    supportsHistory: true,
    supportsShare: true,
    implemented: true,
  },
  {
    id: 'border-radius-preview',
    title: 'Border Radius Preview',
    category: 'css',
    description: 'Preview and generate border-radius CSS',
    keywords: ['border-radius', 'rounded', 'css', 'preview'],
    inputType: 'form',
    outputType: 'code',
    supportsLiveTransform: true,
    supportsFileUpload: false,
    supportsHistory: true,
    supportsShare: true,
    implemented: true,
  },
  {
    id: 'css-units-converter',
    title: 'CSS Units Converter',
    category: 'css',
    description: 'Convert between CSS units (px, rem, em, %)',
    keywords: ['css', 'units', 'px', 'rem', 'em', 'convert'],
    inputType: 'text',
    outputType: 'text',
    supportsLiveTransform: true,
    supportsFileUpload: false,
    supportsHistory: true,
    supportsShare: true,
    implemented: true,
  },
  {
    id: 'css-grid-generator',
    title: 'CSS Grid Generator',
    category: 'css',
    description: 'Visually create CSS Grid layouts',
    keywords: ['grid', 'css', 'layout', 'generator'],
    inputType: 'form',
    outputType: 'code',
    supportsLiveTransform: true,
    supportsFileUpload: false,
    supportsHistory: true,
    supportsShare: true,
    implemented: true,
  },

  // HTML Tools (new category)
  {
    id: 'html-to-jsx',
    title: 'HTML to JSX',
    category: 'html',
    description: 'Convert HTML to JSX/React syntax',
    keywords: ['html', 'jsx', 'react', 'convert'],
    inputType: 'code',
    outputType: 'code',
    supportsLiveTransform: true,
    supportsFileUpload: true,
    supportsHistory: true,
    supportsShare: true,
    implemented: true,
  },
  {
    id: 'html-minifier',
    title: 'HTML Minifier',
    category: 'html',
    description: 'Minify HTML by removing whitespace',
    keywords: ['html', 'minify', 'compress', 'compact'],
    inputType: 'code',
    outputType: 'code',
    supportsLiveTransform: true,
    supportsFileUpload: true,
    supportsHistory: true,
    supportsShare: true,
    implemented: true,
  },
  {
    id: 'html-beautifier',
    title: 'HTML Beautifier',
    category: 'html',
    description: 'Format and indent HTML code',
    keywords: ['html', 'format', 'beautify', 'indent'],
    inputType: 'code',
    outputType: 'code',
    supportsLiveTransform: true,
    supportsFileUpload: true,
    supportsHistory: true,
    supportsShare: true,
    implemented: true,
  },
  {
    id: 'html-preview',
    title: 'HTML Preview',
    category: 'html',
    description: 'Live preview of HTML code',
    keywords: ['html', 'preview', 'render', 'live'],
    inputType: 'code',
    outputType: 'preview',
    supportsLiveTransform: true,
    supportsFileUpload: true,
    supportsHistory: true,
    supportsShare: true,
    implemented: true,
  },
  {
    id: 'html-to-markdown',
    title: 'HTML to Markdown',
    category: 'html',
    description: 'Convert HTML to Markdown syntax',
    keywords: ['html', 'markdown', 'convert', 'md'],
    inputType: 'code',
    outputType: 'text',
    supportsLiveTransform: true,
    supportsFileUpload: true,
    supportsHistory: true,
    supportsShare: true,
    implemented: true,
  },
  {
    id: 'markdown-to-html',
    title: 'Markdown to HTML',
    category: 'html',
    description: 'Convert Markdown to HTML',
    keywords: ['markdown', 'html', 'convert', 'md'],
    inputType: 'text',
    outputType: 'code',
    supportsLiveTransform: true,
    supportsFileUpload: true,
    supportsHistory: true,
    supportsShare: true,
    implemented: true,
  },
  {
    id: 'html-table-generator',
    title: 'HTML Table Generator',
    category: 'html',
    description: 'Generate HTML tables from data',
    keywords: ['html', 'table', 'generate', 'grid'],
    inputType: 'text',
    outputType: 'code',
    supportsLiveTransform: true,
    supportsFileUpload: true,
    supportsHistory: true,
    supportsShare: true,
    implemented: true,
  },

  // Converter Tools (new category)
  {
    id: 'xml-to-json',
    title: 'XML to JSON',
    category: 'converter',
    description: 'Convert XML to JSON format',
    keywords: ['xml', 'json', 'convert', 'parse'],
    inputType: 'text',
    outputType: 'json',
    supportsLiveTransform: true,
    supportsFileUpload: true,
    supportsHistory: true,
    supportsShare: true,
    implemented: true,
  },
  {
    id: 'csv-to-json',
    title: 'CSV to JSON',
    category: 'converter',
    description: 'Convert CSV data to JSON',
    keywords: ['csv', 'json', 'convert', 'parse'],
    inputType: 'text',
    outputType: 'json',
    supportsLiveTransform: true,
    supportsFileUpload: true,
    supportsHistory: true,
    supportsShare: true,
    implemented: true,
  },
  {
    id: 'yaml-to-toml',
    title: 'YAML to TOML',
    category: 'converter',
    description: 'Convert YAML to TOML format',
    keywords: ['yaml', 'toml', 'convert'],
    inputType: 'text',
    outputType: 'text',
    supportsLiveTransform: true,
    supportsFileUpload: true,
    supportsHistory: true,
    supportsShare: true,
    implemented: true,
  },
  {
    id: 'toml-to-json',
    title: 'TOML to JSON',
    category: 'converter',
    description: 'Convert TOML to JSON format',
    keywords: ['toml', 'json', 'convert'],
    inputType: 'text',
    outputType: 'json',
    supportsLiveTransform: true,
    supportsFileUpload: true,
    supportsHistory: true,
    supportsShare: true,
    implemented: true,
  },
  {
    id: 'binary-text',
    title: 'Binary ↔ Text',
    category: 'converter',
    description: 'Convert between binary and text',
    keywords: ['binary', 'text', 'convert', 'ascii'],
    inputType: 'text',
    outputType: 'text',
    supportsLiveTransform: true,
    supportsFileUpload: false,
    supportsHistory: true,
    supportsShare: true,
    implemented: true,
  },
  {
    id: 'svg-to-css',
    title: 'SVG to CSS',
    category: 'converter',
    description: 'Convert SVG to CSS background-image',
    keywords: ['svg', 'css', 'background', 'convert'],
    inputType: 'code',
    outputType: 'code',
    supportsLiveTransform: true,
    supportsFileUpload: true,
    supportsHistory: true,
    supportsShare: true,
    implemented: true,
  },
  {
    id: 'unit-converter',
    title: 'Unit Converter',
    category: 'converter',
    description: 'Convert between units (length, weight, temp)',
    keywords: ['unit', 'convert', 'metric', 'imperial'],
    inputType: 'form',
    outputType: 'text',
    supportsLiveTransform: true,
    supportsFileUpload: false,
    supportsHistory: false,
    supportsShare: false,
    implemented: true,
  },
  {
    id: 'morse-code',
    title: 'Morse Code',
    category: 'converter',
    description: 'Encode and decode Morse code',
    keywords: ['morse', 'code', 'encode', 'decode'],
    inputType: 'text',
    outputType: 'text',
    supportsLiveTransform: true,
    supportsFileUpload: false,
    supportsHistory: true,
    supportsShare: true,
    implemented: true,
  },
  {
    id: 'roman-numeral',
    title: 'Roman Numeral',
    category: 'converter',
    description: 'Convert between Roman and Arabic numerals',
    keywords: ['roman', 'numeral', 'convert', 'number'],
    inputType: 'text',
    outputType: 'text',
    supportsLiveTransform: true,
    supportsFileUpload: false,
    supportsHistory: true,
    supportsShare: true,
    implemented: true,
  },

  // Media Tools
  {
    id: 'youtube-downloader',
    title: 'YouTube Video Downloader',
    category: 'media',
    description: 'Get direct download link for YouTube videos',
    keywords: ['youtube', 'download', 'video', 'mp4'],
    inputType: 'form',
    outputType: 'text',
    supportsLiveTransform: false,
    supportsFileUpload: false,
    supportsHistory: true,
    supportsShare: true,
    implemented: true,
  },
  {
    id: 'instagram-downloader',
    title: 'Instagram Video Downloader',
    category: 'media',
    description: 'Get direct download link for Instagram videos/reels',
    keywords: ['instagram', 'reel', 'download', 'video'],
    inputType: 'form',
    outputType: 'text',
    supportsLiveTransform: false,
    supportsFileUpload: false,
    supportsHistory: true,
    supportsShare: true,
    implemented: true,
  },
  {
    id: 'youtube-to-mp3',
    title: 'YouTube to MP3',
    category: 'media',
    description: 'Convert YouTube video to downloadable MP3 link',
    keywords: ['youtube', 'mp3', 'audio', 'download', 'convert'],
    inputType: 'form',
    outputType: 'text',
    supportsLiveTransform: false,
    supportsFileUpload: false,
    supportsHistory: true,
    supportsShare: true,
    implemented: true,
  },
]

export function getToolsByCategory(category: ToolCategory): ToolMetadata[] {
  return tools.filter((tool) => tool.category === category)
}

export function getToolById(id: string): ToolMetadata | undefined {
  return tools.find((tool) => tool.id === id)
}

export function searchTools(query: string): ToolMetadata[] {
  const lowerQuery = query.toLowerCase()
  return tools.filter(
    (tool) =>
      tool.title.toLowerCase().includes(lowerQuery) ||
      tool.description.toLowerCase().includes(lowerQuery) ||
      tool.keywords.some((kw) => kw.toLowerCase().includes(lowerQuery))
  )
}

export function getCategories(): ToolCategory[] {
  return Object.keys(categoryLabels) as ToolCategory[]
}

// Group tools by category for UI rendering
export interface CategoryGroup {
  slug: ToolCategory;
  name: string;
  icon: string;
  tools: ToolMetadata[];
}

export function getToolRegistry(): CategoryGroup[] {
  const categories = getCategories();
  return categories.map((cat) => ({
    slug: cat,
    name: categoryLabels[cat],
    icon: categoryIcons[cat],
    tools: getToolsByCategory(cat),
  }));
}

// Alias for backward compatibility
export const TOOL_REGISTRY = getToolRegistry();

// Featured tools (most commonly used)
export const FEATURED_TOOLS = [
  'json-beautifier',
  'json-to-typescript',
  'jwt-decoder',
  'timestamp-converter',
  'base64',
  'uuid-generator',
  'regex-tester',
  'case-converter',
  'color-converter',
];

// Helper to generate tool URL
export function getToolUrl(categorySlug: string, toolId: string): string {
  return `/tools/${categorySlug}/${toolId}`;
}

// Helper to get tool by slug
export function getToolBySlug(categorySlug: string, toolSlug: string): ToolMetadata | undefined {
  return tools.find((t) => t.category === categorySlug && t.id === toolSlug);
}

// Re-export Tool type for convenience
export type Tool = ToolMetadata;
